#!/usr/bin/env python3
"""Convert a Chrome/PyTorch profiler trace into CSV/XLSX tables.

The trace UI is useful for timelines, but bottleneck hunting usually starts with
tables: top operations by total duration, stream usage, and long individual
events. This script reads .json or .json.gz traces generated by SGLang profiling.
"""

from __future__ import annotations

import argparse
import csv
import gzip
import json
import math
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable


def load_trace(path: Path) -> dict[str, Any]:
    opener = gzip.open if path.suffix == ".gz" else open
    with opener(path, "rt", encoding="utf-8") as f:
        return json.load(f)


def percentile(values: list[float], pct: float) -> float:
    if not values:
        return 0.0
    xs = sorted(values)
    k = (len(xs) - 1) * pct / 100.0
    lo = math.floor(k)
    hi = math.ceil(k)
    if lo == hi:
        return xs[lo]
    return xs[lo] * (hi - k) + xs[hi] * (k - lo)


def trace_stem(path: Path) -> str:
    name = path.name
    for suffix in (".trace.json.gz", ".json.gz", ".trace.json", ".json"):
        if name.endswith(suffix):
            return name[: -len(suffix)]
    return path.stem


def collect_metadata(events: Iterable[dict[str, Any]]) -> tuple[dict[tuple[Any, Any], str], dict[Any, str]]:
    thread_names: dict[tuple[Any, Any], str] = {}
    process_names: dict[Any, str] = {}
    for event in events:
        if event.get("ph") != "M":
            continue
        args = event.get("args") or {}
        name = event.get("name")
        if name == "thread_name" and "name" in args:
            thread_names[(event.get("pid"), event.get("tid"))] = str(args["name"])
        elif name == "process_name" and "name" in args:
            process_names[event.get("pid")] = str(args["name"])
    return thread_names, process_names


def pick_stream(event: dict[str, Any], thread_name: str) -> str:
    args = event.get("args") or {}
    for key in ("stream", "stream id", "stream_id", "cuda_stream"):
        if key in args:
            return str(args[key])
    match = re.search(r"\bstream\s+(\S+)", thread_name, re.IGNORECASE)
    if match:
        return match.group(1)
    return ""


def classify_event(name: str, cat: str, process_name: str, thread_name: str) -> str:
    text = f"{name} {cat} {process_name} {thread_name}".lower()
    if any(x in text for x in ("nixl", "ucx", "transfer", "bootstrap", "send", "recv")):
        return "transfer"
    if any(x in text for x in ("memcpy", "memset", "copy_", "copykernel", "copy ")):
        return "memcpy"
    if any(x in text for x in ("synchronize", "cudaevent", "cudastreamwaitevent", "wait", "barrier")):
        return "sync_wait"
    if any(x in text for x in ("attention", "flashinfer", "trtllm", "mha", "pagedattention")):
        return "attention"
    if any(x in text for x in ("gemm", "matmul", "cutlass", "cublas", "linear")):
        return "gemm"
    if any(x in text for x in ("sampling", "softmax", "topk", "logits")):
        return "sampling_logits"
    if thread_name.lower().startswith("stream"):
        return "gpu_kernel"
    if "cuda" in text:
        return "cuda_api"
    return "other"


def compact_args(args: dict[str, Any], limit: int = 2000) -> str:
    if not args:
        return ""
    text = json.dumps(args, ensure_ascii=False, sort_keys=True, default=str)
    if len(text) > limit:
        return text[: limit - 3] + "..."
    return text


def event_rows(trace: dict[str, Any], min_dur_us: float, max_events: int) -> list[dict[str, Any]]:
    events = trace.get("traceEvents") or []
    thread_names, process_names = collect_metadata(events)
    complete_events = [
        e
        for e in events
        if e.get("ph") == "X" and isinstance(e.get("dur"), (int, float)) and e.get("dur", 0) >= min_dur_us
    ]
    if not complete_events:
        return []

    min_ts = min(float(e.get("ts", 0.0)) for e in complete_events)
    rows: list[dict[str, Any]] = []

    for idx, event in enumerate(complete_events, start=1):
        if max_events > 0 and len(rows) >= max_events:
            break
        pid = event.get("pid")
        tid = event.get("tid")
        process_name = process_names.get(pid, str(pid))
        thread_name = thread_names.get((pid, tid), str(tid))
        name = str(event.get("name", ""))
        cat = str(event.get("cat", ""))
        args = event.get("args") or {}
        dur_us = float(event.get("dur", 0.0))
        ts_us = float(event.get("ts", 0.0))
        stream = pick_stream(event, thread_name)
        category = classify_event(name, cat, process_name, thread_name)

        rows.append(
            {
                "idx": idx,
                "category": category,
                "process": process_name,
                "thread": thread_name,
                "stream": stream,
                "name": name,
                "cat": cat,
                "start_ms": round((ts_us - min_ts) / 1000.0, 6),
                "dur_ms": round(dur_us / 1000.0, 6),
                "pid": pid,
                "tid": tid,
                "args": compact_args(args),
            }
        )
    return rows


def summarize_by_name(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    groups: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        groups[(row["category"], row["name"])].append(row)

    summary = []
    for (category, name), items in groups.items():
        durations = [float(x["dur_ms"]) for x in items]
        streams = Counter(str(x["stream"]) for x in items if x["stream"])
        threads = Counter(str(x["thread"]) for x in items if x["thread"])
        summary.append(
            {
                "category": category,
                "name": name,
                "count": len(items),
                "total_ms": round(sum(durations), 6),
                "avg_ms": round(sum(durations) / len(durations), 6),
                "p50_ms": round(percentile(durations, 50), 6),
                "p95_ms": round(percentile(durations, 95), 6),
                "max_ms": round(max(durations), 6),
                "top_streams": "; ".join(f"{k}:{v}" for k, v in streams.most_common(5)),
                "top_threads": "; ".join(f"{k}:{v}" for k, v in threads.most_common(5)),
            }
        )
    return sorted(summary, key=lambda x: float(x["total_ms"]), reverse=True)


def summarize_by_stream(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    groups: dict[tuple[str, str, str], list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        key = (str(row["process"]), str(row["thread"]), str(row["stream"]))
        groups[key].append(row)

    summary = []
    for (process, thread, stream), items in groups.items():
        durations = [float(x["dur_ms"]) for x in items]
        categories = Counter(str(x["category"]) for x in items)
        names = Counter(str(x["name"]) for x in items)
        summary.append(
            {
                "process": process,
                "thread": thread,
                "stream": stream,
                "count": len(items),
                "total_ms": round(sum(durations), 6),
                "avg_ms": round(sum(durations) / len(durations), 6),
                "p95_ms": round(percentile(durations, 95), 6),
                "max_ms": round(max(durations), 6),
                "categories": "; ".join(f"{k}:{v}" for k, v in categories.most_common(5)),
                "top_ops": "; ".join(f"{k}:{v}" for k, v in names.most_common(5)),
            }
        )
    return sorted(summary, key=lambda x: float(x["total_ms"]), reverse=True)


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if rows:
        fieldnames = list(rows[0].keys())
    else:
        fieldnames = []
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def maybe_write_xlsx(path: Path, sheets: dict[str, list[dict[str, Any]]]) -> bool:
    try:
        import pandas as pd  # type: ignore
    except ImportError:
        return False

    with pd.ExcelWriter(path, engine="openpyxl") as writer:
        for sheet_name, rows in sheets.items():
            pd.DataFrame(rows).to_excel(writer, sheet_name=sheet_name[:31], index=False)
            worksheet = writer.sheets[sheet_name[:31]]
            worksheet.freeze_panes = "A2"
            worksheet.auto_filter.ref = worksheet.dimensions
            for col in worksheet.columns:
                max_len = 0
                col_letter = col[0].column_letter
                for cell in col[:200]:
                    max_len = max(max_len, len(str(cell.value or "")))
                worksheet.column_dimensions[col_letter].width = min(max(max_len + 2, 10), 80)
    return True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("trace", type=Path, help="Path to .trace.json, .json, or .json.gz")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Output directory. Defaults to <trace_stem>_tables next to the trace.",
    )
    parser.add_argument(
        "--min-dur-us",
        type=float,
        default=0.0,
        help="Only export events whose duration is at least this many microseconds.",
    )
    parser.add_argument(
        "--long-event-ms",
        type=float,
        default=1.0,
        help="Threshold for the long_events table.",
    )
    parser.add_argument(
        "--max-events",
        type=int,
        default=0,
        help="Maximum number of detail events to export. 0 means no limit.",
    )
    parser.add_argument("--xlsx", action="store_true", help="Also write an .xlsx workbook if pandas/openpyxl are installed.")
    parser.add_argument("--top", type=int, default=20, help="Number of top summary rows to print.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    trace_path = args.trace.expanduser().resolve()
    if not trace_path.exists():
        raise SystemExit(f"Trace file not found: {trace_path}")

    out_dir = args.out_dir
    if out_dir is None:
        out_dir = trace_path.with_name(f"{trace_stem(trace_path)}_tables")
    out_dir = out_dir.expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    trace = load_trace(trace_path)
    rows = event_rows(trace, min_dur_us=args.min_dur_us, max_events=args.max_events)
    by_name = summarize_by_name(rows)
    by_stream = summarize_by_stream(rows)
    long_events = sorted(
        [row for row in rows if float(row["dur_ms"]) >= args.long_event_ms],
        key=lambda x: float(x["dur_ms"]),
        reverse=True,
    )

    stem = trace_stem(trace_path)
    paths = {
        "events": out_dir / f"{stem}_events.csv",
        "summary_by_name": out_dir / f"{stem}_summary_by_name.csv",
        "summary_by_stream": out_dir / f"{stem}_summary_by_stream.csv",
        "long_events": out_dir / f"{stem}_long_events.csv",
    }
    write_csv(paths["events"], rows)
    write_csv(paths["summary_by_name"], by_name)
    write_csv(paths["summary_by_stream"], by_stream)
    write_csv(paths["long_events"], long_events)

    xlsx_path = out_dir / f"{stem}_trace_summary.xlsx"
    wrote_xlsx = False
    if args.xlsx:
        wrote_xlsx = maybe_write_xlsx(
            xlsx_path,
            {
                "summary_by_name": by_name,
                "summary_by_stream": by_stream,
                "long_events": long_events,
                "events": rows,
            },
        )

    print(f"Trace: {trace_path}")
    print(f"Events exported: {len(rows)}")
    print(f"Output directory: {out_dir}")
    for label, path in paths.items():
        print(f"{label}: {path}")
    if args.xlsx:
        if wrote_xlsx:
            print(f"xlsx: {xlsx_path}")
        else:
            print("xlsx: skipped because pandas/openpyxl is not installed")

    print("\nTop operations by total duration:")
    for row in by_name[: args.top]:
        print(
            f"{row['total_ms']:>12.3f} ms  {row['count']:>8}x  "
            f"{row['category']:<16}  {str(row['name'])[:100]}"
        )

    print("\nTop streams/threads by total duration:")
    for row in by_stream[: args.top]:
        stream = row["stream"] or "-"
        print(
            f"{row['total_ms']:>12.3f} ms  {row['count']:>8}x  "
            f"stream={stream:<8} thread={str(row['thread'])[:32]}"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
